### ISSUE TITLE
Last 100 commits not grouped by contributor

### ISSUE THREAD

**Issue by lucasBertola** [denis-mludek/gitbrowser#6]
HI denis !
I found a problem!
Last 100 comit not grouped by contributor :)

Thx

**Comment by denis-mludek** [comment]
Hi Lucas,

You're absolutely right. Gonna fix it soon :)

**Comment by lucasBertola** [comment]
Thank you for your speedy reply !

**Comment by denis-mludek** [comment]
Fixed.

**Comment by lucasBertola** [comment]
Thx !
